apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://reading_user:reading_pass@mongodb-service:27017/readingappdb?authSource=admin"
